### ISSUE TITLE
creare/verificare profili utenti WP

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/opendatasicilia.it#1]
- [x] #2
- [x] inserire @dennisangemi 
- [x] inserire @gabacode

**Comment by aborruso** [comment]
Ciao @dennisangemi @gabacode @gbvitrano se seguite le [istruzioni](https://github.com/opendatasicilia/opendatasicilia.it/discussions/18) per puntare al nuovo hosting, potrete entrare come admin su http://opendatasicilia.it/wp-admin/

**Comment by gbvitrano** [comment]
Le mie credenziali non funzionano, posso provare un recupero password o si creo problemi al DB?

![2021-11-28_10h49_26](https://user-images.githubusercontent.com/20488693/143763270-6a0ce2da-7bf3-4424-aa61-89a9e0ec90d1.png)

**Comment by dennisangemi** [comment]
@gbvitrano non funzionavano nemmeno le mie e le ho recuperate. Stai attento perché la mail che permette di effettuare il cambio era finita tra le spam

**Comment by aborruso** [comment]
Certo, vai di recupero

**Comment by gbvitrano** [comment]
Ok grazie grazie 😊

Giovan Battista Vitrano - mobile - @gbvitrano

Il dom 28 nov 2021, 11:05 Andrea Borruso ***@***.***> ha
scritto:
