### ISSUE TITLE
Completamento e Ottimizzazione Sezione Raduni (e Schiticchi)

### ISSUE THREAD

**Issue by picomiles** [opendatasicilia/opendatasicilia.it#10]
Nel sito tramite menù si accede già ad una sezione che raccoglie alcuni dei raduni e "schiticchi" di ODS; completare la sezione e, se opportuno, ottimizzarla

**Comment by aborruso** [comment]
Il lavoro fatto, mi pare buono (è nei menu).

Quindi chiudo. Nel caso riaprite
