### ISSUE TITLE
Inserimento link mancanti

### ISSUE THREAD

**Issue by picomiles** [opendatasicilia/opendatasicilia.it#11]
Verifica ed inserimento nel menu del sito dei link ODS mancanti (ad esempio T'ansignari, repo Github, ecc.)

**Comment by aborruso** [comment]
@picomiles vedi tu cosa manca ancora e chiudi nel caso

Grazie

**Comment by dennisangemi** [comment]
Ho motivo di credere tutti i link relativi ai nostri progetti e ai nostri output a cui fa riferimento @picomiles saranno opportunamente inseriti nel catalogo. Chiudo questa issue e in futuro ne aprirò una per compilare il catalogo quando lo schema sarà solido #74
