### ISSUE TITLE
Tradurre in italiano le categorie delle Discussions

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/opendatasicilia.it#19]
Cambiarle [qui](https://github.com/opendatasicilia/opendatasicilia.it/discussions/categories).

Si può prendere spunto da https://github.com/opendatasicilia/informa-covid19/discussions

**Comment by gabacode** [comment]
Le ho [tradotte](https://github.com/opendatasicilia/opendatasicilia.it/discussions/categories), prendendo "spunto" (C&P)

**Comment by aborruso** [comment]
Grazie
