### ISSUE TITLE
Saltati gli autori nell'import

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/opendatasicilia.it#24]
Come ha notato @dennisangemi , sono saltati gli autori.

Rifaccio l'import io (il precedente l'aveva fatto l'azienda)

### Discussed in https://github.com/opendatasicilia/opendatasicilia.it/discussions/23

<div type='discussions-op-text'>

<sup>Originally posted by **dennisangemi** November 28, 2021</sup>
Ciao @aborruso, per caso sono saltati gli autori o è "normale" in fase di transizione? https://opendatasicilia.it/author/opendat1/

![image](https://user-images.githubusercontent.com/77018886/143774706-d64a4e2a-d781-4d30-9dec-299fecac3c11.png)
</div>

**Comment by aborruso** [comment]
Per risolvere ho dovuto fare l'import, assegnano a mano i nomi degli autori al nome utente.

**Comment by dennisangemi** [comment]
Grazie mille @aborruso
