### ISSUE TITLE
In molti articoli le immagini sono saltate

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/opendatasicilia.it#26]
In molti articoli le immagini sono saltate, bisogna aprire gli articoli e ricaricarli, qualcuno l'ho fatto ma ne restano ancora tanti

_Originally posted by @gbvitrano in https://github.com/opendatasicilia/opendatasicilia.it/discussions/22#discussioncomment-1712942_

**Comment by aborruso** [comment]
Ciao @gbvitrano ma avviene per tutti i post, o per alcuni sì e per altri no?

Nel caso sarebbe molto utile un caso in cui l'import è andato bene e uno in cui è andato male.

In ogni caso, non lo faremo a mano. Abbiamo il DB e faremo un trova e sostituisci.

Grazie

**Comment by gbvitrano** [comment]
Il problema avviene per alcuni post, li devo controllarli ancora tutti, per ora ho risolto aprendo l'articolo, selezionato l'immagine mancante ed ho aggiornato il collegamento.

**Comment by aborruso** [comment]
> Il problema avviene per alcuni post, li devo controllarli ancora tutti, per ora ho risolto aprendo l'articolo, selezionato l'immagine mancante ed ho aggiornato il collegamento.

Non lo fare a mano, sono tanti.

Appena puoi, fammi sapere per favore un caso ok e un caso "rotto" (da non correggere).

**Comment by aborruso** [comment]
> Il problema avviene per alcuni post, li devo controllarli ancora tutti, per ora ho risolto aprendo l'articolo, selezionato l'immagine mancante ed ho aggiornato il collegamento.

Non lo fare a mano, sono tanti.

Appena puoi, fammi sapere per favore un caso ok e un caso "rotto" (da non correggere).

**Comment by gbvitrano** [comment]
Articolo https://opendatasicilia.it/2017/08/29/palermo-3d-maps-wrld/

ecco un esempio - Lato utente
![image](https://user-images.githubusercontent.com/20488693/143844266-a5fe1197-7fd0-4f9e-841e-e7816ff0541b.png)

Lato Admin 
![image](https://user-images.githubusercontent.com/20488693/143844192-95d2c99f-6d27-4e3a-96ea-67b0a5af90ea.png)

**Comment by aborruso** [comment]
Ciao @gbvitrano basta l'URL, grazie :)

Mi serve (scusami se mi ripeto), anche un caso positivo.

Grazie

**Comment by gbvitrano** [comment]
Palermohub è uno degli articoli completi 

https://opendatasicilia.it/2018/08/06/palermohub/ 

In quest'altro alcune immagini ci sono altre no
https://opendatasicilia.it/2019/06/12/palermo-popolazione-residente-per-cittadinanza-upl-quartiere-e-circoscrizione-2018/

**Comment by aborruso** [comment]
Nota per me: migrare dal server vecchio, la cartella `/home/ondata/domains/wp.ondata.it/public_html/wp-content/uploads/sites/2`

**Comment by gabacode** [comment]
Credo sia un problema relativo al certificato SSL inesistente (essendo il dominio aggiunto da /etc/hosts). Il problema sembra coinvolgere solo le immagini hostate su altri domini, con errore `net::ERR_CERT_AUTHORITY_INVALID`
@gbvitrano prova ad utilizzare http al posto di https sulle pagine in cui non caricano le immagini.

**Comment by aborruso** [comment]
Gab farò tutto io con import mappatura dei Path nuovi.
La cosa è presidiata

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il lun 6 dic 2021, 13:20 Gabriele Scalici ***@***.***> ha
scritto:

**Comment by aborruso** [comment]
Ciao, ho fatto le modifiche del caso. Due le cose da risolvere:

- i puntamenti a path "sbagliati", sul vecchio server (la questione HTTP, HTTPS è secondaria rispetto a questo);
- nomi di file errati. C'erano alcuni nomi file con caratteri accentati; su db erano memorizzati con accento (ad esempio `accussì.png`, nel filesystem invece c'era `accuss#U00ec.png`.

Queste le due operazioni fatte:

1. su db

```
update `wp0z_posts` set post_content =
replace(post_content,'http://wp.ondata.it/sicilia/wp-content/uploads/sites/2','https://opendatasicilia.it/wp-content/uploads');
```

2. su filesystem

```bash
find ./ -name "*#*" | grep '#U00e0' | while read line;do nome=$(echo $line | sed -r 's/^(.+?)(#U00e0)(.+)$/\1à\3/');echo $nome;cp "$line" "$nome";done
find ./ -name "*#*" | grep '#U00ec' | while read line;do nome=$(echo $line | sed -r 's/^(.+?)(#U00ec)(.+)$/\1ì\3/');echo $nome;cp "$line" "$nome";done
```


Per il momento la chiudo. Per i test, c'è da svuotare la cache
