### ISSUE TITLE
Creare un dominio di terzo livello per la versione web

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/opendatasicilia.it#45]
Ho messo su una [branch](https://github.com/opendatasicilia/opendatasicilia.it/tree/dev) con un sito iniziale che seguirà gli aggiornamenti di questa Discussion.

_Originally posted by @gabacode in https://github.com/opendatasicilia/opendatasicilia.it/discussions/28#discussioncomment-1789047_

@gabacode se mi dai l'OK potremmo fare puntare `dev.opendatasicilia.it` al tuo branch di prova (se contiene l'HTML di output)

**Comment by gabacode** [comment]
Credo che si possa collegare, ho messo un CNAME all'interno della nuova branch gh-pages. [Settings](https://github.com/opendatasicilia/opendatasicilia.it/settings/pages)

**Comment by aborruso** [comment]
Grazie

**Comment by dennisangemi** [comment]
Ciao @gabacode e grazie. È normale che non si vedano le immagini in questa fase ?

![image](https://user-images.githubusercontent.com/77018886/145775472-c17e5a8b-0005-437c-a078-f4e7bb92ca3e.png)

**Comment by gabacode** [comment]
@dennisangemi dovrebbe essere risolto in b846c1b7fa0bbe11c70bdbc018391907959a5f8b prova a dare un refresh alla pagina

**Comment by aborruso** [comment]
> Credo che si possa collegare, ho messo un CNAME all'interno della nuova branch gh-pages. [Settings](https://github.com/opendatasicilia/opendatasicilia.it/settings/pages)

e secondo te avevo chiuso la issue, senza "collegare"  :)
