### ISSUE TITLE
Rimuovere slack da header

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/opendatasicilia.it#48]
Non lo usiamo

![image](https://user-images.githubusercontent.com/30607/145724987-321177f1-4b62-4116-a2ca-55546386aaf3.png)

**Comment by gbvitrano** [comment]
fatto

**Comment by dennisangemi** [comment]
nei single posts è ancora presente (se non sbaglio)

**Comment by aborruso** [comment]
> nei single posts è ancora presente (se non sbaglio)

io non ce l'ho

**Comment by dennisangemi** [comment]
Ho aggiornato la pagina più volte. Magari è un problema temporaneo. Chiudo

![image](https://user-images.githubusercontent.com/77018886/145725990-eee69807-55e2-4cdc-a131-6a06a48e08be.png)
