### ISSUE TITLE
togliere http://nonportale.opendatasicilia.it/ dalla sezione "cose nostre" perchè

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/opendatasicilia.it#51]
perchè
http://nonportale.opendatasicilia.it/
ora non funziona, in quanto non espone le risorse.

Fu creato in un periodo storico in cui non c'era il portale istituzionale open data della Regione Sicilia.

Se si vuole mantenere nel nuovo sito di ODS, bisogna prima mettere mano al codice su Github, individuando anche dove si trova il file di Google spreadsheet in cui furono censite le risorse che facevano da sorgente a http://nonportale.opendatasicilia.it/

Propongo di toglierlo temporaneamente dall'elenco delle "cose nostre".

**Comment by gbvitrano** [comment]
fatto
