### ISSUE TITLE
Creare pagina 404

### ISSUE THREAD

**Issue by gabacode** [opendatasicilia/opendatasicilia.it#55]
Come accennato precedentemente via chat Telegram con @dennisangemi , sarebbe utile creare una pagina 404 Not Found con una illustrazione carina da utilizzare in caso di errore 404

**Comment by gbvitrano** [comment]
ecco il mitico john
![404](https://user-images.githubusercontent.com/20488693/145796442-f5d81d87-bf0f-48d3-9c4b-ce26e79385f0.gif)

**Comment by gbvitrano** [comment]
gira gira... e jhon è arrivato fin qui :-) la pagina quella la progettate voi 
![Acquisisci schermata Web_13-12-2021_151043_opendatasicilia it](https://user-images.githubusercontent.com/20488693/145827761-83e06868-a1e4-40a2-8e1e-8db684f17219.jpeg)

**Comment by dennisangemi** [comment]
Una cosa del genere potrebbe andar bene?

![Uploading image.png…]()

**Comment by gbvitrano** [comment]
Al posto del tasto Indietro metti il un form per la ricerca/ricerca avanzata.  Devi dare la possibilità di cercare la pagina ho l'argomento

**Comment by dennisangemi** [comment]
@gbvitrano potrei inserire sia il tasto indietro che il motore di ricerca?

**Comment by gbvitrano** [comment]
il tasto indietro serve a poco. Se hai digitato un indirizzo errato, il tasto indietro dove ti porta? Solitamente l'utente tende a tornare alla home page o fare una ricerca. 
Più del tasto Indietro puoi inserite un Torna alla home

**Comment by dennisangemi** [comment]
In effetti ha senso quello che dici. Grazie! Mi ero fatto ingannare da questo:

![image](https://user-images.githubusercontent.com/77018886/145897000-68c7d945-cd88-4633-9f08-6f0a2e6bdf16.png)

**Comment by gbvitrano** [comment]
un pò vivace :-) :-)

**Comment by dennisangemi** [comment]
@gbvitrano @gabacode se pensate possa andare bene, chiudete pure e grazie

Paradossalmente questa è una delle pagine che mi piace di più hahaha

![image](https://user-images.githubusercontent.com/77018886/145897608-3addf784-d6b8-46f8-ba28-ed499508d9b3.png)

**Comment by gbvitrano** [comment]
@dennisangemi non dimenticare mai il cerca in tutto il template, metti un'icona dopo l'ultimo menù, in questo caso Progetti,
fai attenzione alle distanze, Cliccando sul tasto di ricerca che succede? quanto sarà lungo il form per la ricerca...? occhio agli spazi

**Comment by dennisangemi** [comment]
> metti un'icona dopo l'ultimo menù, in questo caso Progetti

Fatto, trovi tutto nel [prototipo](https://xd.adobe.com/view/c9fc700a-2a14-4765-b529-af35e93fe73b-9caf/) compresi i dettagli sulla lunghezza

**Comment by gbvitrano** [comment]
Sono tutti comportamenti diversi al click sull'icona del cerca
![2021-12-13_23h40_16](https://user-images.githubusercontent.com/20488693/145900383-2385fcb7-648c-480f-b25c-d6fc3a906b8b.png)
![2021-12-13_23h41_11](https://user-images.githubusercontent.com/20488693/145900494-a74051e3-775b-4d53-ba50-567d833d7da1.png)
![2021-12-13_23h41_50](https://user-images.githubusercontent.com/20488693/145900564-30707c1c-319f-4995-a7eb-7bfa2d813d87.png)
![2021-12-13_23h42_50](https://user-images.githubusercontent.com/20488693/145900747-7c8f2fe5-c1e0-4a68-bd69-20a00a851553.png)
![2021-12-13_23h43_02](https://user-images.githubusercontent.com/20488693/145900755-78bf9651-f4ab-43f1-a515-4f229d04d721.png)

**Comment by gbvitrano** [comment]
![2021-12-13_23h46_51](https://user-images.githubusercontent.com/20488693/145901222-48c73426-1882-470d-916c-ef9dccd09227.png)

![image](https://user-images.githubusercontent.com/20488693/145901260-e07dda64-c3de-4ffb-ba9e-1378823b8a82.png)

**Comment by dennisangemi** [comment]
Non credo di poter definire questo tipo di comportamenti con Adobe XD. Credo siano animazioni che verranno introdotte da @gabacode (?) ma è giusto cominciarci a pensare

**Comment by dennisangemi** [comment]
p.s. @gbvitrano spostiamoci su nuova issue se credo che la pag 404 sia ok

**Comment by gabacode** [comment]
> Non credo di poter definire questo tipo di comportamenti con Adobe XD. Credo siano animazioni che verranno introdotte da @gabacode (?) ma è giusto cominciarci a pensare

Potremmo mettere qualcosa di simile al dropdown che c'è su [comuni-italiani](https://infocomuni.eu/) ma che fetch i contenuti del sito.

**Comment by dennisangemi** [comment]
@gabacode ho generato SVG dell'illustrazione 404, adesso la puoi scaricare da [XD](https://xd.adobe.com/view/c9fc700a-2a14-4765-b529-af35e93fe73b-9caf/screen/ed8227b8-cc09-4313-b865-b342c4173814/specs/). Presferisci che io la carichi su GH?

**Comment by gabacode** [comment]
Grazie @dennisangemi! Se vuoi puoi metterla nella cartella `src/assets/images/` e piu tardi la collego

**Comment by gbvitrano** [comment]
E' un effeto voluto o è un refuso?

![2021-12-14_10h56_33](https://user-images.githubusercontent.com/20488693/146036379-740e4dd9-ac0c-4e3f-8b83-105b236e28ad.png)
