### ISSUE TITLE
Attivare redirect da http a https

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/opendatasicilia.it#57]
Fatto... ho aggiunto le regole al file .htaccess

_Originally posted by @gbvitrano in https://github.com/opendatasicilia/opendatasicilia.it/discussions/54#discussioncomment-1796682_

**Comment by aborruso** [comment]
ciao @gbvitrano ho letto che hai fatto, ma se io apro il dominio in http (uso firefox) lì rimane.

È normale?

**Comment by dennisangemi** [comment]
> se io apro il dominio in http (uso firefox) lì rimane.

**Comment by gbvitrano** [comment]
strano anche su opera non passa a https, solo edge passa ad https.
Cerco una soluzione

**Comment by gbvitrano** [comment]
Ho provato tre soluzioni, sul mio dominio funzionano, su opendatasicilia.it no. Ho rimesso il file .htaccess originale
Molto probabilmente si deve fare da cpanel

**Comment by gabacode** [comment]
Ho installato [questo plugin](https://it.wordpress.org/plugins/really-simple-ssl/), di solito risolve velocemente.

**Comment by gbvitrano** [comment]
da me no, resta sempre in http ed ho eliminato la chade da tutti i browser

**Comment by gbvitrano** [comment]
adesso funzionaaaaaaa

**Comment by dennisangemi** [comment]
Adesso tutto ok, grazie mille

**Comment by gbvitrano** [comment]
può dipendere dal tipo di spazio e sistema operativo del server?

**Comment by aborruso** [comment]
Grazie @gabacode

**Comment by gbvitrano** [comment]
Grazie grazie 😊

Giovan Battista Vitrano - mobile - @gbvitrano

Il lun 13 dic 2021, 16:30 Gabriele Scalici ***@***.***> ha
scritto:
