### ISSUE TITLE
proposta: creare github action che compila il sito

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/opendatasicilia.it#62]
@gabacode senza impegno, e se possibile, puoi creare un action che compila e pubblica?

È utile perché se qualcuno cambia qualcosa (CSS, immagine, ecc.) e lo vuole vedere online, la può runnare.

Potrebbe anche attivarsi al limite a ogni push in dev.

Grazie

**Comment by gabacode** [comment]
Sì, è un qualcosa di necessario, soprattutto quando saremo in produzione con WordPress e si dovranno aggiungere i nuovi post automaticamente. Devo studiarci su un attimino per capire come fare a far persistere la `.cache` tra un build e l'altro, altrimenti riscarica tutto il sito e sono ~500MB a botta.

Di solito con Gatsby, con o senza CMS, utilizzo [Vercel](https://vercel.app/) o [Netlify](https://www.netlify.com/), entrambi gratuiti per progetti no-profits, ed entrambi ottimizzati per l'utilizzo di vari framework js, tra cui Gatsby. Supportano incremental builds, caching, webhooks e tante altre belle cose di default. Sono due piattaforme che mi sentirei di consigliare al di là di tutto, ma mi piacerebbe anche provare a vedere se riesco ad impelmentare incremental builds tramite gh-pages. C'è poca documentazione in giro a riguardo ma devo ancora esplorare bene e fare qualche test su un altro repo.

Nel frattempo, è possibile lanciare il deploy con il comando `npm run deploy` che praticamente fa un build con la cache che si ha in locale, e uppa la cartella `./public` sul branch `gh-pages`.

**Comment by aborruso** [comment]
Netlify è stupenda. Ma se si può fare tutto qui, ancora meglio.

Fai le tue valutazioni anche in termini di tempo richiesto. 
Se farla lì è ok, creiamo uno spazio Netlify con un account di ODS e ti diamo le "chiavi"

**Comment by gabacode** [comment]
> Netlify è stupenda. Ma se si può fare tutto qui, ancora meglio.
> 
> Fai le tue valutazioni anche in termini di tempo richiesto. Se farla lì è ok, creiamo uno spazio Netlify con un account di ODS e ti diamo le "chiavi"

Grazie Andrea, eventualmente mi sa che possiamo fare il login via GitHub e aggiungere il repo, vedo che trova quello di tansignari.
![Screenshot_20211215_142306](https://user-images.githubusercontent.com/38985346/146194334-6ea786d2-a597-470f-ab9e-ca1ea1ec7825.png)

Vi farò presto avere notizie a riguardo.

**Comment by gabacode** [comment]
@aborruso @dennisangemi 
Scusatemi, mi sono dimenticato un dettagli molto importante per quanto riguarda il build.
Prima di lanciare `npm run build` copiare i contenuti file `.env.development` in un nuovo file chiamato `.env.production` altrimenti gatsby darà un errore in fase di build!

**Comment by gabacode** [comment]
Ho creato una [Github action](https://github.com/opendatasicilia/opendatasicilia.it/blob/dev/.github/workflows/deploy.yml) che fa il deploy ad ogni push, e teoricamente tramite [webhook](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#repository_dispatch). Teoricamente perchè a quanto pare su GitHub è fattibile solo dal main branch. L'ho provata su un altro repo e funziona anche tramite webhook. (utile per avviare le actions direttamente da Wordpress)

Alcune riflessioni:
1. Con la cache su npm e gatsby i tempi di build si abbattono drasticamente, ma in qualche modo Netlify "glie le dà" sempre.  Stiamo parlando di minuti di differenza, empiricamente su una sola osservazione (su un build a contenuti invariati):
- GH-Pages (no cache): 6m 25s
- GH-Pages (con cache): 1m 33s (+1m 41s per associare il dominio)
- Netlify: 1m 4s  

Sarebbe interessante provare a fare ulteriori test da questo repo per ulteriori osservazioni.

2. Netlify ha un endpoint che permette di avviare il deploy senza dover aggiungere il token agli header della richiesta.
Esempio:
```
curl -X POST -d {} https://api.netlify.com/build_hooks/hash
```
vs
```
curl -H "Authorization: token {ghtoken}" \
    --request POST \
    --data '{"event_type": "deploy"}' \
    https://api.github.com/repos/{username}/{repo}/dispatches
```
Questo ci eviterebbe di dover utilizzare una ulteriore API per processare la richiesta e tenere al sicuro il "token". Su Netlify è possibile associare un singolo repo invece di mettere in gioco l'access token, aggiunge un livello di sicurezza in piu.

3. Netlify ha una massimo di 300 minuti di build mensili e 1 build alla volta per la versione free. I limiti di GitHub sono [decisamente](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration) piu alti.

4. Netlify consente di pubblicare diversi build per diverse branches su diversi indirizzi, quindi credo che il webhook funzionerebbe anche sul dev branch.

Entrambe le soluzioni hanno dei pro, e dei contro. In termini di prestazioni e semplicità d'uso Netlify sembra essere, a mio avviso, piu indicato per l'utilizzo che potremmo farne. Ulteriori test sono richiesti per maggiori analisi.

**Comment by gabacode** [comment]
L'action c'è, per ora chiudo.
