### ISSUE TITLE
Problema WP: dicono di noi

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/opendatasicilia.it#68]
Stavo googlando e ho visto questo risultato 

![Screenshot_20211231-143707_Chrome](https://user-images.githubusercontent.com/77018886/147828675-470d5aaa-d082-417b-996d-f2bec2c479d7.jpg)

Faccio click ma la pagina non esiste

https://www.google.com/url?sa=t&source=web&rct=j&url=https://opendatasicilia.it/parlano-di-noi-2/&ved=2ahUKEwi3ute0kY71AhVzhf0HHeFuBHcQFnoECAQQAQ&usg=AOvVaw1nZsRoAaKBQDqYzS237gLf

Che succede? Si può risolvere?

**Comment by gabacode** [comment]
@dennisangemi ho settato un 301 redirect dalla pagina `parlano-di-noi-2` alla pagina `parlano-di-noi` usando il plugin Redirector. Fammi sapere se ha risolto anche da te.

**Comment by dennisangemi** [comment]
Tutto risolto @gabacode . Grazie mille ;)
