### ISSUE TITLE
Sito WP: Leggibilità e larghezza post

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/opendatasicilia.it#70]
Ciao @gbvitrano, personalmente ritengo che nell'attuale versione del sito wp andrebbe aumentato lo spazio tra i bordi del display e il div contenente il corpo del blog post. Si potrebbe pensare, ad esempio, di aumentare solo lo spazio dal bordo destro e incolonnare il testo a sinistra. Insomma, in qualche modo ridurrei la larghezza del corpo del post per migliorarne la leggibilità. Te ne puoi occupare per favore? Thx

**Comment by dennisangemi** [comment]
Se possibile ridurrei leggermente anche il font del post

**Comment by gbvitrano** [comment]
Vuoi che riduca il Content...? se no ho capito male :-)


![2022-01-11_02h44_59](https://user-images.githubusercontent.com/20488693/148866884-bf79ef2e-b6d9-4cfa-af70-bb783dd244cc.png)
![2022-01-11_02h45_23](https://user-images.githubusercontent.com/20488693/148866889-450633f5-1d14-47d3-b275-ddc569dd941d.png)

**Comment by gbvitrano** [comment]
Content e testo ridotto
![2022-01-11_02h53_06](https://user-images.githubusercontent.com/20488693/148867561-81df3e05-cda7-4f1c-8a52-7d93c2f46c9e.png)

**Comment by dennisangemi** [comment]
Grazie mille @gbvitrano . Proprio quello che intendevo dire. Scusami per i termini non appropriati ;)
