### ISSUE TITLE
Aggiornamenti e ottimizzazioni Wordpress

### ISSUE THREAD

**Issue by picomiles** [opendatasicilia/opendatasicilia.it#8]
Sarebbe opportuno verificare l'eventuale necessità di aggiornare Wordpress e, a margine, capire se vanno intraprese ulteriori azioni di ottimizzazione riguardanti tema, plugin, ecc.

**Comment by dennisangemi** [comment]
Io chiuderei questa issue perché abbiamo trovato le soluzioni che fanno al caso nostro
